databases:
  - name: shopping_list
    databaseName: db.sqlite3
    user: shopping_list

services:
  - type: web
    name: shopping_list
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'gunicorn shopping_list.wsgi:application'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mysite
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
